/*
 * Copyright (c) 2020-2023 Macronix International Co. LTD. All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

#ifndef _SECUREFLASH_ERROR_H_
#define _SECUREFLASH_ERROR_H_

#define SECUREFLASH_SUCCESS                     0
#define SECUREFLASH_ERROR_INITIAL              -1
#define SECUREFLASH_ERROR_ALLOCATION           -2
#define SECUREFLASH_ERROR_DEVICE               -3
#define SECUREFLASH_ERROR_CREATE_SESSION       -4
#define SECUREFLASH_ERROR_CLOSE_SESSION        -5
#define SECUREFLASH_ERROR_SESSION_ID_NOT_EXIST -6
#define SECUREFLASH_ERROR_SESSION_EXHAUST      -7
#define SECUREFLASH_ERROR_SECURE_READ          -8
#define SECUREFLASH_ERROR_SECURE_PROGRAM       -9
#define SECUREFLASH_ERROR_SECURE_ERASE         -10
#define SECUREFLASH_ERROR_READ                 -11
#define SECUREFLASH_ERROR_PROGRAM              -12
#define SECUREFLASH_ERROR_ERASE                -13
#define SECUREFLASH_ERROR_RPMC_WRITE_ROOT_KEY  -14
#define SECUREFLASH_ERROR_RPMC_UPDATE_HMAC_KEY -15
#define SECUREFLASH_ERROR_GET_PUF              -16
#define SECUREFLASH_ERROR_GET_UID              -17
#define SECUREFLASH_ERROR_GET_TRNG             -18
#define SECUREFLASH_ERROR_GET_MC               -19
#define SECUREFLASH_ERROR_INCREASE_MC          -20
#define SECUREFLASH_ERROR_UNPROVISIONED        -21
#define SECUREFLASH_ERROR_PARTITION_EXIST      -22
#define SECUREFLASH_ERROR_PARTITION_NOT_EXIST  -23
#define SECUREFLASH_ERROR_PARTITION_EXHAUST    -24
#define SECUREFLASH_ERROR_WRITE_PACKET         -25
#define SECUREFLASH_ERROR_READ_PACKET          -26
#define SECUREFLASH_ERROR_CRYPTO_SERVICE       -27
#define SECUREFLASH_ERROR_DEVICE_BUSY          -28
#define SECUREFLASH_ERROR_SECURITY_COMMAND     -29
#define SECUREFLASH_ERROR_INVALID_PROVISION    -30
#define SECUREFLASH_ERROR_PROVISION            -31
#define SECUREFLASH_ERROR_ZONE_ISOLATION       -33
#define SECUREFLASH_ERROR_IAP                  -34
#define SECUREFLASH_ERROR_SECURE_INIT          -35
#define SECUREFLASH_ERROR_SFDP_SFTBL           -36
#define SECUREFLASH_ERROR_ENTER_SECURITY_FIELD -37
#define SECUREFLASH_ERROR_EXIT_SECURITY_FIELD  -38
#define SECUREFLASH_ERROR_INVALID_ARGUMENT     -39
#define SECUREFLASH_ERROR_ILLEGAL_ACCESS       -40
#define SECUREFLASH_ERROR_INSUFFICIENT_MEMORY  -41
#define SECUREFLASH_ERROR_BAD_STATE            -42
#define SECUREFLASH_ERROR_UNSUPPORTED_DEVICE   -43
#define SECUREFLASH_ERROR_GET_PROVISION_INFO   -44
#define SECUREFLASH_ERROR_SECURE_DEINIT        -45
#endif /* _SECUREFLASH_ERROR_H_ */
